### ISSUE TITLE
Buying upgrade QOL changes

### ISSUE THREAD

**Issue by videomaximum** [cyferlawyn/arcinc#10]
Buy x10, x25, x50, x100, and Max would be nice

Also changing the auto buy to have a slightly longer delay before activating as well as slightly getting faster  at buying upgrades the longer it autobuys would be great QOL changes

**Comment by cyferlawyn** [comment]
Also changing the auto buy to have a slightly longer delay before activating as well as slightly getting faster at buying upgrades the longer it autobuys would be great QOL changes

Implemented as requested, multibuy i still feel is not needed now that you can pretty much buy 1000 in less than 5 sec.
